query AIPoweredSearch(
  $query: String!
  $type: String!
  $language: String
  $queryType: EGWQueryTypeEnum
  $orderBy: SortOrderEnum
  $filter: SearchInputFilterInput
) {
  search(
    query: $query
    type: $type
    language: $language
    queryType: $queryType
    orderBy: $orderBy
    filter: $filter
  ) {
    totalCount
    info {
      hasNextPage
      hasPreviousPage
    }
    items {
      weight
      answer
      snippet
      paraId
      publication {
        id
        title
        code
        languageCode
        isAudioBook
        folderId
        permission
        author {
          firstName
          lastName
          middleName
        }
        pageCount
      }
      paragraph {
        refCodes {
          short
        }
        chapterId
        paraId
        content
        metadata {
          date
          paraId
          bibleReference {
            book
            chapter
            verses
          }
        }
      }
    }
  }
}
